[package]
name = "usaco-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
async-lock = "3.4.0"
async-trait = "0.1.83"
reqwest = { version = "0.12.9", features = ["json"] }
secret-service = { version = "4.0.0", features = ["rt-async-io-crypto-openssl"] }
thiserror = "1.0.66"
